Feature/new palette button
SethBurns/coloRandom pull request #3
Opened 2023-04-11 21:47 UTC by SethBurns

## What is the feature?
Button added below color boxes. Styling to match client's request. Added font styles in HTML.
Fixed requested changes from Jason.
## How you implemented the solution?
CSS and HTML changes.
## Does it impact any other area of the project?
Creates button for functionality.
## Any changes in the UI (Screenshots)?
New button added.
## How to test the feature (A test scenario or any new setup)?
No tests needed.

2023-04-11 22:01 UTC, jalbe0076 approved these changes

2023-04-11 23:32 UTC, mbenfowler requested changes
Looking at the spec, we may wanna go ahead and make sure all main elements are equidistant from each other and centered on the page!

<img width="918" alt="Screenshot 2023-04-11 at 7 23 35 PM" src="https://user-images.githubusercontent.com/32660020/231310577-723a60b2-6101-4c09-b2e0-fbd943906245.png">

2023-04-12 00:02 UTC, mbenfowler commented on index.html
> +            </div>
why is the over-arching div class named `"box-title"`?

2023-04-12 00:59 UTC, SethBurns commented
Fixed space between children of body using flexbox. Changed some class names to be more appropriate naming conventions.

2023-04-12 01:00 UTC, mbenfowler approved these changes

2023-04-12 01:03 UTC, jalbe0076 approved these changes

2023-04-12 01:03 UTC, merged